ARG device_type
ARG registry
ARG version
FROM ${registry}/ppd-${device_type}-base:${version}

# Docker script to set up training docker image.
LABEL maintainer="Yun Zhu(zhuyun@ppdai.com)"

# Configure environment
ARG project_home_in_docker
ENV PROJECT_HOME_IN_DOCKER=${project_home_in_docker}

# Assembling project
ADD ./codes ${PROJECT_HOME_IN_DOCKER}/codes
ADD ./confs ${PROJECT_HOME_IN_DOCKER}/confs
ADD ./scripts ${PROJECT_HOME_IN_DOCKER}/bin
